version: '3.8'
services:
  spring-app:
    image: librarymanagementapp:latest
    ports:
      - "8081:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_PROFILES_ACTIVE: "test"
    networks:
      - backend
  mysql-db:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_pms
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - backend
networks:
  backend:
    driver: bridge
